import { Book } from "src/api/book/book.entity";

export const ALL_BOOKS_MOCK: Book[] = [
  {
    author: "Михаил Булгаков",
    name: "Мастер и Маргарита",
    description: "",
    cover: " ",
    id: 1,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Собачье сердце",
    description: "",
    cover: " ",
    id: 2,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Илья Ильф, Евгений Петров",
    name: "Двенадцать стульев",
    description: "",
    cover: " ",
    id: 3,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Мёртвые души",
    description: "",
    cover: " ",
    id: 4,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Граф Монте-Кристо",
    description: "",
    cover: " ",
    id: 5,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Илья Ильф, Евгений Петров",
    name: "Золотой теленок",
    description: "",
    cover: " ",
    id: 6,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Эрих Мария Ремарк",
    name: "Три товарища",
    description: "",
    cover: " ",
    id: 7,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Виктор Гюго",
    name: "Отверженные",
    description: "",
    cover: " ",
    id: 8,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Евгений Онегин",
    description: "",
    cover: " ",
    id: 9,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Преступление и наказание",
    description: "",
    cover: " ",
    id: 10,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Война и мир",
    description: "",
    cover: " ",
    id: 11,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Повести Белкина",
    description: "",
    cover: " ",
    id: 12,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Ревизор",
    description: "",
    cover: " ",
    id: 13,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Село Степанчиково и его обитатели",
    description: "",
    cover: " ",
    id: 14,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иван Тургенев",
    name: "Отцы и дети",
    description: "",
    cover: " ",
    id: 15,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Три мушкетера",
    description: "",
    cover: " ",
    id: 16,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Палата № 6",
    description: "",
    cover: " ",
    id: 17,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Братья Карамазовы",
    description: "",
    cover: " ",
    id: 18,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Артур Конан Дойль",
    name: "Собака Баскервилей",
    description: "",
    cover: " ",
    id: 19,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Идиот",
    description: "",
    cover: " ",
    id: 20,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иван Тургенев",
    name: "Рудин",
    description: "",
    cover: " ",
    id: 21,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Артур Конан Дойль",
    name: "Приключения Шерлока Холмса",
    description: "",
    cover: " ",
    id: 22,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Грибоедов",
    name: "Горе от ума",
    description: "",
    cover: " ",
    id: 23,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Дубровский",
    description: "",
    cover: " ",
    id: 24,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Драма на охоте",
    description: "",
    cover: " ",
    id: 25,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Капитанская дочка",
    description: "",
    cover: " ",
    id: 26,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Униженные и оскорблённые",
    description: "",
    cover: " ",
    id: 27,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Воскресение",
    description: "",
    cover: " ",
    id: 28,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иван Тургенев",
    name: "Дворянское гнездо",
    description: "",
    cover: " ",
    id: 29,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Рассказы",
    description: "",
    cover: " ",
    id: 30,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Эрих Мария Ремарк",
    name: "Триумфальная арка",
    description: "",
    cover: " ",
    id: 31,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Подросток",
    description: "",
    cover: " ",
    id: 32,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Эрнест Хемингуэй",
    name: "Старик и море",
    description: "",
    cover: " ",
    id: 33,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Жюль Верн",
    name: "Двадцать тысяч лье под водой",
    description: "",
    cover: " ",
    id: 34,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Борис Васильев",
    name: "А зори здесь тихие",
    description: "",
    cover: " ",
    id: 35,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Анна Каренина",
    description: "",
    cover: " ",
    id: 36,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Даниель Дефо",
    name: "Робинзон Крузо",
    description: "",
    cover: " ",
    id: 37,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Шарлотта Бронте",
    name: "Джейн Эйр",
    description: "",
    cover: " ",
    id: 38,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Лермонтов",
    name: "Герой нашего времени",
    description: "",
    cover: " ",
    id: 39,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Руслан и Людмила",
    description: "",
    cover: " ",
    id: 40,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Жюль Верн",
    name: "Дети капитана Гранта",
    description: "",
    cover: " ",
    id: 41,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Бесы",
    description: "",
    cover: " ",
    id: 42,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Виконт де Бражелон, или Десять лет спустя",
    description: "",
    cover: " ",
    id: 43,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Двадцать лет спустя",
    description: "",
    cover: " ",
    id: 44,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Эрих Мария Ремарк",
    name: "Черный обелиск",
    description: "",
    cover: " ",
    id: 45,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Шолохов",
    name: "Тихий Дон",
    description: "",
    cover: " ",
    id: 46,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Джек Лондон",
    name: "Белый Клык",
    description: "",
    cover: " ",
    id: 47,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иван Гончаров",
    name: "Обломов",
    description: "",
    cover: " ",
    id: 48,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Детство. Отрочество. Юность",
    description: "",
    cover: " ",
    id: 49,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Вишневый сад",
    description: "",
    cover: " ",
    id: 50,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Белая гвардия",
    description: "",
    cover: " ",
    id: 51,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Юлиан Семенов",
    name: "Семнадцать мгновений весны",
    description: "",
    cover: " ",
    id: 52,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Григорий Белых, Л. Пантелеев",
    name: "Республика ШКИД",
    description: "",
    cover: " ",
    id: 53,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Вениамин Каверин",
    name: "Два капитана",
    description: "",
    cover: " ",
    id: 54,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Леонид Филатов",
    name: "Про Федота-стрельца, удалого молодца",
    description: "",
    cover: " ",
    id: 55,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Графиня де Монсоро",
    description: "",
    cover: " ",
    id: 56,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Станислав Лем",
    name: "Солярис",
    description: "",
    cover: " ",
    id: 57,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Вечера на хуторе близ Диканьки",
    description: "",
    cover: " ",
    id: 58,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Владимир Обручев",
    name: "Земля Санникова",
    description: "",
    cover: " ",
    id: 59,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Игрок",
    description: "",
    cover: " ",
    id: 60,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Артур Конан Дойль",
    name: "Возвращение Шерлока Холмса",
    description: "",
    cover: " ",
    id: 61,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Аркадий и Борис Стругацкие",
    name: "Пикник на обочине",
    description: "",
    cover: " ",
    id: 62,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Дядя Ваня",
    description: "",
    cover: " ",
    id: 63,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Пиковая дама",
    description: "",
    cover: " ",
    id: 64,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Шолохов",
    name: "Судьба человека",
    description: "",
    cover: " ",
    id: 65,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Алексей Толстой",
    name: "Пётр Первый",
    description: "",
    cover: " ",
    id: 66,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Грин",
    name: "Алые паруса",
    description: "",
    cover: " ",
    id: 67,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Волков",
    name: "Волшебник Изумрудного города",
    description: "",
    cover: " ",
    id: 68,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Тарас Бульба",
    description: "",
    cover: " ",
    id: 69,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Беляев",
    name: "Человек-амфибия",
    description: "",
    cover: " ",
    id: 70,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Бедные люди",
    description: "",
    cover: " ",
    id: 71,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Федор Достоевский",
    name: "Записки из Мёртвого дома",
    description: "",
    cover: " ",
    id: 72,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Борис Пастернак",
    name: "Доктор Живаго",
    description: "",
    cover: " ",
    id: 73,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Алексей Толстой",
    name: "Хождение по мукам",
    description: "",
    cover: " ",
    id: 74,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Медный всадник",
    description: "",
    cover: " ",
    id: 75,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Пушкин",
    name: "Борис Годунов",
    description: "",
    cover: " ",
    id: 76,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Джордж Оруэлл",
    name: "1984",
    description: "",
    cover: " ",
    id: 77,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Чайка",
    description: "",
    cover: " ",
    id: 78,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Записки юного врача",
    description: "",
    cover: " ",
    id: 79,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Морфий",
    description: "",
    cover: " ",
    id: 80,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Иван Васильевич",
    description: "",
    cover: " ",
    id: 81,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Владимир Богомолов",
    name: "Момент истины (В августе 44-го)",
    description: "",
    cover: " ",
    id: 82,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Аркадий и Борис Стругацкие",
    name: "Трудно быть богом",
    description: "",
    cover: " ",
    id: 83,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Михаил Булгаков",
    name: "Бег",
    description: "",
    cover: " ",
    id: 84,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Константин Симонов",
    name: "Живые и мертвые",
    description: "",
    cover: " ",
    id: 85,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Кавказский пленник",
    description: "",
    cover: " ",
    id: 86,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Валентин Катаев",
    name: "Белеет парус одинокий",
    description: "",
    cover: " ",
    id: 87,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Дюма",
    name: "Сорок пять",
    description: "",
    cover: " ",
    id: 88,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Александр Островский",
    name: "Бесприданница",
    description: "",
    cover: " ",
    id: 89,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иван Тургенев",
    name: "Записки охотника",
    description: "",
    cover: " ",
    id: 90,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Марк Твен",
    name: "Приключения Тома Сойера",
    description: "",
    cover: " ",
    id: 91,
    rate: 0,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Антон Чехов",
    name: "Три сестры",
    description: "",
    cover: " ",
    id: 92,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Лев Толстой",
    name: "Хаджи-Мурат",
    description: "",
    cover: " ",
    id: 93,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Шинель",
    description: "",
    cover: " ",
    id: 94,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Марк Твен",
    name: "Приключения Гекльберри Финна",
    description: "",
    cover: " ",
    id: 95,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Габриэль Гарсиа Маркес",
    name: "Сто лет одиночества",
    description: "",
    cover: " ",
    id: 96,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Жюль Верн",
    name: "Таинственный остров",
    description: "",
    cover: " ",
    id: 97,
    rate: 4,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Иоганн Вольфганг фон Гёте",
    name: "Фауст",
    description: "",
    cover: " ",
    id: 98,
    rate: 2,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Виктор Гюго",
    name: "Собор Парижской Богоматери",
    description: "",
    cover: " ",
    id: 99,
    rate: 3,
    reviews: [],
    fullBook: "",
  },
  {
    author: "Николай Гоголь",
    name: "Вий",
    description: "",
    cover: " ",
    id: 100,
    rate: 1,
    reviews: [],
    fullBook: "",
  },
];
