services:
  client:
    stdin_open: true # docker run -i
    # tty: true        # docker run -t
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80

  database:
    image: postgres:15
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    env_file:
    - ./backend/.env
    command: yarn start:dev
    ports:
      - 3001:3001

  # nginx:
  #   # depends_on:
  #   #   - api
  #   #   - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "3080:80"
  #   links:
  #     - client