services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - .:/usr/src/app
    command: yarn serve build
    ports:
      - 3003:3000

  database:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
  
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    env_file:
    - ./backend/.env
    command: yarn start:dev
    ports:
      - 3004:3001