services:
  database:
    image: postgres:15
    # command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100m"
  
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: yarn start:dev
    ports:
      - 3004:3001
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200m"